"""Build train_formatted_v11.jsonl = v9 with ONLY bit_manipulation traces
regenerated by bit_manip_trace_v5 (derivation-first). All other categories are
copied byte-identical from v9.

v5 emits only fully-derivable traces; bit_manip problems whose solver rule uses
families v5 does not derive (NAND/NOR/MAJ/XOR3/Popcount/invariant-k3) are
dropped and logged. Correctness is gated the same way as v9: a regenerated
trace is kept only if its computed answer == the v9 record's answer.

Usage:
    python -m scripts.build_v11_bitmanip \
        --v9 datasets/processed/train_formatted_v9.jsonl \
        --out datasets/processed/train_formatted_v11.jsonl
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
from pathlib import Path

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

from src.data.bit_manip_solver_v3 import parse_examples as bm_parse, solve as bm_solve
from src.data.bit_manip_trace_v5 import generate_trace as bm_trace_v5
from src.data.format_training import format_training_example

TOKENIZER = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"


def _v5_trace(prompt: str):
    pairs, q = bm_parse(prompt)
    if not pairs or q is None:
        return None
    rule = bm_solve(pairs)
    if rule is None:
        return None
    return bm_trace_v5(rule, pairs, q)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--v9", type=Path, default=Path("datasets/processed/train_formatted_v9.jsonl"))
    ap.add_argument("--out", type=Path, default=Path("datasets/processed/train_formatted_v11.jsonl"))
    args = ap.parse_args()

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(TOKENIZER, trust_remote_code=True)

    raw_lines = args.v9.read_text().splitlines()
    print(f"[v11] read {len(raw_lines)} v9 records from {args.v9}", flush=True)

    out_lines: list[str] = []
    kept_bm = dropped_bm = 0
    drop_reasons = collections.Counter()
    nonbm_hash = hashlib.sha256()                  # over verbatim non-bm lines
    counts = collections.Counter()

    for line in raw_lines:
        rec = json.loads(line)
        task = rec["task_type"]
        if task != "bit_manipulation":
            out_lines.append(line)                 # verbatim -> byte-identical
            nonbm_hash.update((line + "\n").encode())
            counts[task] += 1
            continue
        res = _v5_trace(rec["prompt"])
        if res is None:
            dropped_bm += 1
            drop_reasons["v5_no_trace"] += 1
            continue
        trace, answer = res
        if str(answer).strip() != str(rec["answer"]).strip():
            dropped_bm += 1
            drop_reasons["answer_mismatch"] += 1
            continue
        fmt = format_training_example(
            prompt=rec["prompt"], answer=str(rec["answer"]),
            reasoning_trace=trace, tokenizer=tok,
        )
        tot = len(tok.encode(fmt["text"]))
        p_tok = len(tok.encode(fmt["prompt_text"]))
        new_rec = {
            "id": rec["id"], "task_type": task, "prompt": rec["prompt"],
            "answer": rec["answer"], "reasoning_trace": trace,
            "source": rec.get("source", "solver"),
            "text": fmt["text"], "prompt_text": fmt["prompt_text"],
            "completion_text": fmt["completion_text"],
            "n_tokens_total": tot, "n_tokens_prompt": p_tok,
            "n_tokens_completion": tot - p_tok,
        }
        out_lines.append(json.dumps(new_rec))
        kept_bm += 1
        counts[task] += 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out_lines) + "\n")

    print(f"[v11] wrote {len(out_lines)} records -> {args.out}", flush=True)
    print(f"[v11] bit_manipulation: kept {kept_bm}, dropped {dropped_bm} "
          f"({dict(drop_reasons)})", flush=True)
    print("[v11] per-category counts:")
    for t, c in counts.most_common():
        print(f"  {c:5d}  {t}", flush=True)
    print(f"[v11] non-bit_manip lines sha256 {nonbm_hash.hexdigest()[:16]} "
          f"(verify against v9 separately)", flush=True)
    # token budget on regenerated bm
    bm_toks = [json.loads(l)["n_tokens_completion"] for l in out_lines
               if json.loads(l)["task_type"] == "bit_manipulation"]
    bm_toks.sort()
    print(f"[v11] bm completion tokens: min={bm_toks[0]} med={bm_toks[len(bm_toks)//2]} "
          f"max={bm_toks[-1]}  over2000={sum(1 for t in bm_toks if t>2000)}", flush=True)


if __name__ == "__main__":
    main()
